apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: data-interface-for-salesforce-price-bulk-get
  name: data-interface-for-salesforce-price-bulk-get
spec:
  replicas: 1
  selector:
    matchLabels:
      run: data-interface-for-salesforce-price-bulk-get
  strategy:
    rollingUpdate:
  template:
    metadata:
      labels:
        run: data-interface-for-salesforce-price-bulk-get
    spec:
      hostname: data-interface-for-salesforce-price-bulk-get
      containers:
        - name: data-interface-for-salesforce-price-bulk-get
          image: latonaio/data-interface-for-salesforce-price-bulk-get
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "9000"
            - name: TZ
              value: Asia/Tokyo
          ports:
            - containerPort: 9000
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: "200Mi"
            requests:
              cpu: "0.5"
              memory: "100Mi"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: data-interface-for-salesforce-price-bulk-get
  name: data-interface-for-salesforce-price-bulk-get
spec:
  selector:
    run: data-interface-for-salesforce-price-bulk-get
  type: ClusterIP
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
